version: "3.7"
services:
  # MySQL
  ttt-mysql:
    image: mysql:5.7.39
    volumes:
      - ./config/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=TTT
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"